name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest]
        rust: [stable, beta]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --release --verbose
      - name: Run all days
        run: cargo run --release --verbose all
